name: Auto generate learn manifest

on:
  push:
    branches: [main, learning-manifest]
    paths:
      - 'learning/**'
  pull_request:
    branches: [main, learning-manifest]
    paths:
      - 'learning/**'
  workflow_dispatch:  # Allow manual trigger

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Use Node 18
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Generate Learn manifest
        run: node scripts/generate‑manifest.js

      - name: Check for changes
        id: check_changes
        run: |
          git diff --quiet learning/learn-manifest.json || echo "changes=true" >> $GITHUB_OUTPUT

      - name: Commit and push changes
        if: steps.check_changes.outputs.changes == 'true'
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add learning/learn-manifest.json
          git commit -m "chore: update learn manifest"
          git push