name: Auto generate learn manifest

on:
  push:
    branches: [main, learning-manifest]
  pull_request:
    branches: [main, learning-manifest]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Use Node 18
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - run: npm ci

      - name: Generate Learn manifest
        run: |
          node learning/scripts/generate-manifest.js

      - name: Commit and push changes
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add learning/learn-manifest.json
          git commit -m "chore: update learn manifest"
          git push